# Generated by Django 3.2.9 on 2022-04-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_value',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(null=True, upload_to='answer/', verbose_name='Изображение'),
        ),
    ]
