# Generated by Django 3.2.9 on 2022-02-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(null=True, upload_to='answer/', verbose_name='Изображение'),
        ),
    ]
