# Generated by Django 3.2.9 on 2022-02-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dementia_test.dementiatestcase', verbose_name='Прохождение теста'),
        ),
    ]
