# Generated by Django 3.2.9 on 2022-02-09 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0002_auto_20220208_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Номер вопроса'),
        ),
    ]
