# Generated by Django 3.2.9 on 2022-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0003_auto_20220415_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Значение ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='answer/', verbose_name='Изображение'),
        ),
    ]
