# Generated by Django 3.2.9 on 2022-02-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0003_alter_answer_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('test_case', 'question')},
        ),
    ]
