# Generated by Django 3.2.9 on 2022-02-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0002_alter_answer_test_case'),
        ('dementia_test', '0004_alter_answer_unique_together'),
    ]

    operations = [
    ]
