# Generated by Django 3.2.9 on 2022-04-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0004_auto_20220415_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.IntegerField(blank=True, default='', verbose_name='Количество баллов')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_id', to='dementia_test.answer', verbose_name='id теста')),
            ],
            options={
                'verbose_name': 'Количество баллов за вопрос',
                'verbose_name_plural': 'Количество баллов за вопросы',
            },
        ),
    ]
