# Generated by Django 3.2.9 on 2022-05-15 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0005_resultanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_value',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение ответа'),
        ),
    ]
