# Generated by Django 3.2.9 on 2022-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0005_resultanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemeniaTestCaseAlt',
            fields=[
            ],
            options={
                'verbose_name': 'Прохождение теста (альт.)',
                'verbose_name_plural': 'Прохождения тестов (альт.)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dementia_test.dementiatestcase',),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_value',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(null=True, upload_to='answer/', verbose_name='Изображение'),
        ),
    ]
