# Generated by Django 3.2.9 on 2022-05-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_test', '0006_auto_20220515_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemeniaTestCaseAlt',
            fields=[
            ],
            options={
                'verbose_name': 'Прохождение теста (альт.)',
                'verbose_name_plural': 'Прохождения тестов (альт.)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dementia_test.dementiatestcase',),
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question'], 'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(null=True, upload_to='answer/', verbose_name='Изображение'),
        ),
    ]
