# Generated by Django 3.2.9 on 2021-12-25 11:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("demencia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(default="Деменция.net", max_length=255)),
                ("copyright", models.CharField(default="Благотворительный фонд «Память поколений»", max_length=255)),
                ("meta_description", models.TextField()),
                ("main_section_link", models.CharField(default="Пройти тест", max_length=255)),
                ("main_section_additional", models.TextField()),
                ("about_section", models.CharField(default="О деменции", max_length=255)),
                ("about_section_term", tinymce.models.HTMLField()),
                ("about_section_term_link", models.CharField(default="Подробнее", max_length=255)),
                ("about_section_action_title", models.CharField(default="Помоги близким", max_length=255)),
                ("about_section_action_subtitle", models.CharField(default="Пройди тест с тем кому нужна помощь", max_length=255)),
                ("about_section_info", tinymce.models.HTMLField()),
                ("about_section_link", models.CharField(default="Пройти тест", max_length=255)),
                ("news_section", models.CharField(default="Что нового?", max_length=255)),
                ("news_section_link", models.CharField(default="Перейти к ленте новостей", max_length=255)),
                ("partners_section", models.CharField(default="Кто с нами?", max_length=255)),
                ("partners_section_link", models.CharField(default="Партнеры", max_length=255)),
                ("map_section", models.CharField(default="Куда идти?", max_length=255)),
                ("map_section_link", models.CharField(default="Карта центров профилактики", max_length=255)),
                ("map_section_info", tinymce.models.HTMLField()),
                ("fund_section", models.CharField(default="О фонде", max_length=255)),
                ("fund_section_info", tinymce.models.HTMLField()),
                ("fund_section_link", models.CharField(default="Перейти на сайт фонда", max_length=255)),
            ],
            options={
                "verbose_name": "Системные настройки",
                "verbose_name_plural": "Системные настройки",
            },
        ),
    ]
