# Generated by Django 3.2.9 on 2022-04-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_send_email',
            field=models.BooleanField(default=False, verbose_name='Разрешить отправку писем'),
        ),
    ]
