# Generated by Django 3.2.9 on 2021-12-27 12:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='address',
            field=models.CharField(help_text='Улица, дом, офис', max_length=250, verbose_name='Адрес в городе'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
