# Generated by Django 3.2.9 on 2021-12-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='leftmenuelement',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='mainmenuelement',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='mappoint',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='newsarticle',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='partner',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='slider',
            managers=[
            ],
        ),
    ]
