# Generated by Django 3.2.9 on 2022-03-20 18:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона с указанием кода региона (пример: +7 495 933 00 20 или 8 495 933 00 20)', max_length=20, region='RU', verbose_name='Номер телефона'),
        ),
    ]
