# Generated by Django 3.2.9 on 2022-03-22 13:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0002_alter_mappoint_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='phone_no_secondary',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер телефона с указанием кода региона (пример: +7 495 933 00 20 или 8 495 933 00 20)', max_length=20, region='RU', verbose_name='Номер телефона (дополнительный)'),
        ),
    ]
