# Generated by Django 3.2.9 on 2022-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0002_settings_enable_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='map_section_info',
            field=models.TextField(null=True, verbose_name='Предупреждение'),
        ),
    ]
