# Generated by Django 3.2.9 on 2021-12-26 09:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0002_base_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='map_section_link',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='partners_section_link',
        ),
        migrations.AddField(
            model_name='settings',
            name='fund_section_url',
            field=models.URLField(default='https://pamyatpokoleniy.ru/', max_length=255, verbose_name='Ссылка на сайт фонда'),
        ),
        migrations.AddField(
            model_name='settings',
            name='main_section_additional_link',
            field=models.CharField(default='Подробнее', max_length=255, verbose_name='Название ссылки для доп. информации'),
        ),
        migrations.AddField(
            model_name='settings',
            name='main_section_additional_url',
            field=models.URLField(default='https://душевная.москва/ru-RU/moscow_nko/all_news/card/12871.html', max_length=255, verbose_name='Ссылка на ресурс доп. информации'),
        ),
        migrations.AddField(
            model_name='settings',
            name='map_section_subtitle',
            field=models.CharField(default='Карта центров профилактики', max_length=255, verbose_name='Название ссылки'),
        ),
        migrations.AddField(
            model_name='settings',
            name='partners_section_subtitle',
            field=models.CharField(default='Партнеры', max_length=255, verbose_name='Название ссылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_section',
            field=models.CharField(default='О деменции', max_length=255, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_section_action_subtitle',
            field=models.CharField(default='Пройди тест с тем кому нужна помощь', max_length=255, verbose_name='Подзаголовок действия'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_section_action_title',
            field=models.CharField(default='Помоги близким', max_length=255, verbose_name='Заголовок действия'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_section_info',
            field=tinymce.models.HTMLField(verbose_name='Информация о статистике'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_section_link',
            field=models.CharField(default='Пройти тест', max_length=255, verbose_name='Название ссылки для прохождения теста'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_section_term',
            field=tinymce.models.HTMLField(verbose_name='Определение термина'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_section_term_link',
            field=models.CharField(default='Подробнее', max_length=255, verbose_name='Название ссылки для раскрытия термина'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='copyright',
            field=models.CharField(default='Благотворительный фонд «Память поколений»', max_length=255, verbose_name='Авторское право'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fund_section',
            field=models.CharField(default='О фонде', max_length=255, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fund_section_info',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fund_section_link',
            field=models.CharField(default='Перейти на сайт фонда', max_length=255, verbose_name='Название ссылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='main_section_additional',
            field=models.TextField(verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='main_section_link',
            field=models.CharField(default='Пройти тест', max_length=255, verbose_name='Название ссылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_section',
            field=models.CharField(default='Куда идти?', max_length=255, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='map_section_info',
            field=tinymce.models.HTMLField(verbose_name='Предупреждение'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='meta_description',
            field=models.TextField(verbose_name='Meta описание'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='news_section',
            field=models.CharField(default='Что нового?', max_length=255, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='news_section_link',
            field=models.CharField(default='Перейти к ленте новостей', max_length=255, verbose_name='Название ссылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='partners_section',
            field=models.CharField(default='Кто с нами?', max_length=255, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site_name',
            field=models.CharField(default='Деменция.net', max_length=255, verbose_name='Название сайта'),
        ),
    ]
