# Generated by Django 3.2.9 on 2021-12-27 14:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0002_auto_20211227_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона с указанием кода', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
