# Generated by Django 3.2.9 on 2022-01-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0002_base_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки главной страницы', 'verbose_name_plural': 'Настройки главной страницы'},
        ),
    ]
