# Generated by Django 3.2.9 on 2021-12-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0002_leftmenuelement_mainmenuelement'),
        ('demencia', '0002_slider'),
    ]

    operations = [
    ]
