# Generated by Django 3.2.9 on 2022-01-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0003_alter_mappoint_phone_no'),
        ('demencia', '0003_auto_20211226_1205'),
    ]

    operations = [
    ]
