# Generated by Django 3.2.9 on 2021-12-19 18:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0003_merge_20211219_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='text',
        ),
        migrations.AddField(
            model_name='slider',
            name='url_label',
            field=models.CharField(default='ПОДРОБНЕЕ', max_length=50, verbose_name='Название ссылки'),
        ),
    ]
