# Generated by Django 3.2.9 on 2022-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0003_alter_settings_map_section_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='map_section_info',
            field=models.TextField(blank=True, null=True, verbose_name='Предупреждение'),
        ),
    ]
