# Generated by Django 3.2.9 on 2021-12-24 14:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0004_auto_20211219_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Заполняется автоматически', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Заполняется автоматически', verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Включить/отключить показ на сайте', verbose_name='Активность')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес в городе')),
                ('phone_no', models.CharField(max_length=250, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Точка на карте',
                'verbose_name_plural': 'Точки на карте',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(default=0, help_text='Введите адрес ссылки', max_length=250, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url_label',
            field=models.CharField(default='ПОДРОБНЕЕ', help_text='Введите текст ссылки', max_length=50, verbose_name='Название ссылки'),
        ),
        migrations.AlterField(
            model_name='leftmenuelement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Заполняется автоматически', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='leftmenuelement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Включить/отключить показ на сайте', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='leftmenuelement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Заполняется автоматически', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='mainmenuelement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Заполняется автоматически', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mainmenuelement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Включить/отключить показ на сайте', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='mainmenuelement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Заполняется автоматически', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Заполняется автоматически', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Включить/отключить показ на сайте', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='text',
            field=models.TextField(help_text='Введите текст', verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(help_text='Введите заголовок', max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Заполняется автоматически', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Заполняется автоматически', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='partners/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Включить/отключить показ на сайте', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(help_text='Введите название партнёра', max_length=250, verbose_name='Название партнёра'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Заполняется автоматически', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.URLField(help_text='Введите адрес ссылки', max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Заполняется автоматически', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Включить/отключить показ на сайте', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(help_text='Введите заголовок', max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Заполняется автоматически', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(help_text='Введите адрес ссылки', max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url_label',
            field=models.CharField(default='ПОДРОБНЕЕ', help_text='Введите текст ссылки', max_length=50, verbose_name='Название ссылки'),
        ),
    ]
