# Generated by Django 3.2.9 on 2021-12-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0003_base_settings'),
        ('demencia', '0004_auto_20211219_2127'),
    ]

    operations = [
    ]
