# Generated by Django 3.2.9 on 2021-12-25 14:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0005_merge_0003_base_settings_0004_auto_20211219_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес в городе')),
                ('phone_no', models.CharField(max_length=250, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Точка на карте',
                'verbose_name_plural': 'Точки на карте',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(blank=True, max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url_label',
            field=models.CharField(default='ПОДРОБНЕЕ', max_length=50, verbose_name='Название ссылки'),
        ),
    ]
