# Generated by Django 3.2.9 on 2022-01-22 13:56

from django.db import migrations, models
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0005_auto_20220121_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='main_section_additional',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='main_section_additional_link',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='main_section_additional_url',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='main_section_link',
        ),
        migrations.AddField(
            model_name='settings',
            name='main_section_label',
            field=models.CharField(default='Пройти тест', max_length=255, verbose_name='Название кнопки'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(help_text='Введите адрес ссылки', max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(help_text='Введите адрес ссылки', max_length=250, verbose_name='Ссылка'),
        ),
    ]
