# Generated by Django 3.2.9 on 2022-01-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0007_auto_20220122_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leftmenuelement',
            options={'ordering': ['position'], 'verbose_name': 'Элемент левого меню', 'verbose_name_plural': 'Элементы левого меню'},
        ),
        migrations.AlterModelOptions(
            name='mainmenuelement',
            options={'ordering': ['position'], 'verbose_name': 'Элемент главного меню', 'verbose_name_plural': 'Элементы главного меню'},
        ),
        migrations.AlterModelOptions(
            name='mappoint',
            options={'ordering': ['position'], 'verbose_name': 'Точка на карте', 'verbose_name_plural': 'Точки на карте'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['position'], 'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['position'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AddField(
            model_name='leftmenuelement',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainmenuelement',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slider',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
