# Generated by Django 3.2.9 on 2022-01-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0009_set_position_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftmenuelement',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Можно поменять перетаскиванием на странице списка объектов', verbose_name='Позиция в списке'),
        ),
        migrations.AlterField(
            model_name='mainmenuelement',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Можно поменять перетаскиванием на странице списка объектов', verbose_name='Позиция в списке'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Можно поменять перетаскиванием на странице списка объектов', verbose_name='Позиция в списке'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Можно поменять перетаскиванием на странице списка объектов', verbose_name='Позиция в списке'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Можно поменять перетаскиванием на странице списка объектов', verbose_name='Позиция в списке'),
        ),
    ]
