# Generated by Django 3.2.9 on 2022-02-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0011_auto_20220202_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
