# Generated by Django 3.2.9 on 2022-02-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0012_alter_region_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='demencia.region', verbose_name='Регион'),
        ),
    ]
