# Generated by Django 3.2.9 on 2022-02-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0011_auto_20220202_1514'),
        ('demencia', '0013_alter_mappoint_region'),
    ]

    operations = [
    ]
