# Generated by Django 3.2.9 on 2022-02-07 09:14

import demencia.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0013_auto_20220207_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=demencia.models.SmallHTMLField(help_text='Введите заголовок', max_length=250, verbose_name='Заголовок'),
        ),
    ]
