# Generated by Django 3.2.9 on 2022-03-11 16:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('demencia', '0014_alter_slider_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона с указанием кода региона (пример: +7 (495) 933 00 20)', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='demencia.region', verbose_name='Регион'),
        ),
    ]
