version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  nginx:
    image: nginx:1.21
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/demencia-backend/static
      - media-volume:/demencia-backend/media

  backend:
    image: demencia/demencia_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - static-volume:/demencia-backend/static
      - media-volume:/demencia-backend/media

volumes:
  db_data:
  static-volume:
  media-volume:
