# Generated by Django 3.2.9 on 2022-09-25 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Заполняется автоматически', verbose_name='Дата создания')),
                ('question', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Номер вопроса')),
                ('answer_value', models.CharField(max_length=255, null=True, verbose_name='Значение ответа')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='DementiaTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Заполняется автоматически', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Прохождение теста',
                'verbose_name_plural': 'Прохождения тестов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.IntegerField(blank=True, default='', verbose_name='Количество баллов')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_id', to='demencia_relatives_test.answer', verbose_name='id теста')),
            ],
            options={
                'verbose_name': 'Количество баллов за вопрос',
                'verbose_name_plural': 'Количество баллов за вопросы',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='demencia_relatives_test.dementiatestcase', verbose_name='Прохождение теста'),
        ),
        migrations.CreateModel(
            name='DemeniaTestCaseAlt',
            fields=[
            ],
            options={
                'verbose_name': 'Прохождение теста для родственников (альт.)',
                'verbose_name_plural': 'Прохождения тестов для родственников (альт.)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('demencia_relatives_test.dementiatestcase',),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('test_case', 'question')},
        ),
    ]
